#
# Copyright 2019-2022 Signal Messenger, LLC
# SPDX-License-Identifier: AGPL-3.0-only
#

[workspace]
resolver = "2"
members = [
  "call_sim",
  "mrp",
  "protobuf",
  "src/rust",
  "webrtc-sys",
  "webrtc-sys/build",
]

[workspace.lints.clippy]
unnecessary_wraps = "warn"

[workspace.package]
version = "2.72.1"
authors = ["Calling Team <callingteam@signal.org>"]
